### ISSUE TITLE
Trips for the current day are not displayed even when they are in the cache

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-phone#111]
One of the complaints from users was that they didn't see any trips when they launched the app. While this was sometimes due to the latency in sending the trip to the server and processing it, there is also an error thrown while processing trips for the first load.

Because of the error, we don't process the trips, which means that we don't display them. I am not able to reproduce this in the iOS emulator, but I am able to consistently reproduce this on my android phone. And I know that it was a regression - this used to work without any problems at the beginning of summer.

The error is

```
I/chromium(19270): [INFO:CONSOLE(508)] "currIndex = 1470898800000 currDayTrips = 2", source: file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/js/diary/services.js?ionicCachebuster=14405 (508)
I/chromium(19270): [INFO:CONSOLE(143)] "Got event with args {"from":"broadcast","status":"success"}", source: file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/js/diary/list.js?ionicCachebuster=14405 (143)
I/chromium(19270): [INFO:CONSOLE(26794)] "TypeError: Cannot read property '57acdb3088f6634f22600300' of undefined
I/chromium(19270):     at Object.commonGraph.trip2Common (file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/js/common/services.js?ionicCachebuster=14405:43:47)
I/chromium(19270):     at Object.dh.fillCommonTripCount (file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/js/diary/services.js?ionicCachebuster=14405:242:31)
I/chromium(19270):     at dh.directiveForTrip (file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/js/diary/services.js?ionicCachebuster=14405:258:8)
I/chromium(19270):     at Array.map (native)
I/chromium(19270):     at file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/js/diary/list.js?ionicCachebuster=14405:147:72
I/chromium(19270):     at Scope.$eval (file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/lib/ionic/js/ionic.bundle.js?ionicCachebuster=14405:30395:28)
I/chromium(19270):     at Scope.$apply (file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/lib/ionic/js/ionic.bundle.js?ionicCachebuster=14405:30495:25)
I/chromium(19270):     at file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/js/diary/list.js?ionicCachebuster=14405:144:14
I/chromium(19270):     at Scope.$broadcast (file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/lib/ionic/js/ionic.bundle.js?ionicCachebuster=14405:30718:28)
I/chromium(19270):     at processTripsForDay (file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/js/diary/services.js?ionicCachebuster=14405:512:24)", source: file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/lib/ionic/js/ionic.bundle.js?ionicCachebuster=14405 (26794)
I/chromium(19270): [INFO:CONSOLE(513)] "About to hide 'Processing trips'", source: file:///data/data/edu.berkeley.eecs.emission/app_9361511a-5805-11e6-9812-1e2c9ed655d2/js/diary/services.js?ionicCachebuster=14405 (513)
I/chromium(19270): [INFO:CONSOLE(49)] "INFO:About to execute query SELECT data FROM userCache WHERE key = 'common-trips' AND (type = 'document' OR type = 'rw-document') ORDER BY write_ts DESC LIMIT 1 against userCache", source: file:///android_asset/www/plugins/edu.berkeley.eecs.emission.cordova.unifiedlogger/www/unifiedlogger.js (49)
```

**Comment by shankari** [comment]
Full log is attached.
[logcat.gz](https://github.com/e-mission/e-mission-phone/files/414673/logcat.gz)

**Comment by shankari** [comment]
It looks like there is a race between the load of the diary and the common trips, so when we try to match up the trip to see if it is common, there is no map to compare it with. I can fix this, or @krisma or @sunil07t can take a stab at it to understand the challenges of async work better.

**Comment by shankari** [comment]
I just ran into what appeard to be this issue in the iOS emulator as well. No trips were loaded, but when I pulled to refresh, trips showed up.

The error was 

```
Error: undefined is not an object (evaluating 'tripId')
trip2Common@file:///Users/shankari/Library/Developer/CoreSimulator/Devices/D647A352-18D7-41C8-908E-1D383516F707/data/Containers/Bundle/Application/7A1DDF1C-BDB7-4F4E-95F2-2046A100A572/emission.app/www/js/common/services.js:43:54
fillCommonTripCount@file:///Users/shankari/Library/Developer/CoreSimulator/Devices/D647A352-18D7-41C8-908E-1D383516F707/data/Containers/Bundle/Application/7A1DDF1C-BDB7-4F4E-95F2-2046A100A572/emission.app/www/js/diary/services.js:242:42
directiveForTrip@file:///Users/shankari/Library/Developer/CoreSimulator/Devices/D647A352-18D7-41C8-908E-1D383516F707/data/Containers/Bundle/Application/7A1DDF1C-BDB7-4F4E-95F2-2046A100A572/emission.app/www/js/diary/services.js:258:27
map@[native code]
file:///Users/shankari/Library/Developer/CoreSimulator/Devices/D647A352-18D7-41C8-908E-1D383516F707/data/Containers/Bundle/Application/7A1DDF1C-BDB7-4F4E-95F2-2046A100A572/emission.app/www/js/diary/list.js:153:75
$eval@file:///Users/shankari/Library/Developer/CoreSimulator/Devices/D647A352-18D7-41C8-908E-1D383516F707/data/Containers/Bundle/Application/7A1DDF1C-BDB7-4F4E-95F2-2046A100A572/emission.app/www/lib/ionic/js/ionic.bundle.js:30395:28
$apply@file:///Users/shankari/Library/Developer/CoreSimulator/Devices/D647A352-18D7-41C8-908E-1D383516F707/data/Containers/Bundle/Application/7A1DDF1C-BDB7-4F4E-95F2-2046A100A572/emission.app/www/lib/ionic/js/ionic.bundle.js:30495:30
file:///Users/shankari/Library/Developer/CoreSimulator/Devices/D647A352-18D7-41C8-908E-1D383516F707/data/Containers/Bundle/Application/7A1DDF1C-BDB7-4F4E-95F2-2046A100A572/emission.app/www/js/diary/list.js:150:20
$broadcast@file:///Users/shankari/Library/Developer/CoreSimulator/Devices/D647A352-18D7-41C8-908E-1D383516F707/data/Containers/Bundle/Application/7A1DDF1C-BDB7-4F4E-95F2-2046A100A572/emission.app/www/lib/ionic/js/ionic.bundle.js:30718:33
processTripsForDay@file:///Users/shankari/Library/Developer/CoreSimulator/Devices/D647A352-18D7-41C8-908E-1D383516F707/data/Containers/Bundle/Application/7A1DDF1C-BDB7-4F4E-95F2-2046A100A572/emission.app/www/js/diary/services.js:512:34
file:///Users/shankari/Library/Developer/CoreSimulator/Devices/D647A352-18D7-41C8-908E-1D383516F707/data/Containers/Bundle/Application/7A1DDF1C-BDB7-4F4E-95F2-2046A100A572/emission.app/www/js/diary/services.js:376:19
promiseReactionJob@[native code]
```

**Comment by shankari** [comment]
The stacktrace from the code is

```
    /*
     * Returns the common trip corresponding to the specified tripId
     */
    commonGraph.trip2Common = function(tripId) {
        return commonGraph.data.trip2CommonMap[tripId];
    };
```

```
  dh.fillCommonTripCount = function(tripWrapper) {
      var cTrip = CommonGraph.trip2Common(tripWrapper.data.id);
      if (!angular.isUndefined(cTrip)) {
          tripWrapper.common_count = cTrip.trips.length;
      }
  };
```

```
  dh.directiveForTrip = function(trip) {
    var retVal = {};
    retVal.data = trip;
    retVal.style = style_feature;
    retVal.onEachFeature = onEachFeature;
    retVal.pointToLayer = pointFormat;
    retVal.start_place = trip.start_place;
    retVal.end_place = trip.end_place;
    retVal.stops = trip.stops;
    retVal.sections = trip.sections;
    retVal.tripSummary = trip.tripSummary;
    dh.fillCommonTripCount(retVal);
    // Hardcoding to avoid repeated nominatim calls
    // retVal.start_place.properties.displayName = "Start";
    // retVal.start_place.properties.displayName = "End";
    return retVal;
  };
```

```
    $scope.$on(Timeline.UPDATE_DONE, function(event, args) {
      console.log("Got event with args "+JSON.stringify(args));
      $scope.$apply(function() {
          $scope.data = Timeline.data;
          $scope.datepickerObject.inputDate = Timeline.data.currDay.toDate();
          $scope.data.currDayTripWrappers = Timeline.data.currDayTrips.map(
            DiaryHelper.directiveForTrip);
          $ionicScrollDelegate.scrollTop(true);
      });
    });
```

**Comment by shankari** [comment]
Given that we start loading with the dashboard, this is not a major issue any more. On the other hand, it is annoying and easily fixable. On the third hand, we should really restructure the whole diary/common code interaction to be more promise oriented.

Going to poke at the dashboard first and see if there are more immediate bugs.

**Comment by shankari** [comment]
@juemura @sunil07t @Fernando-Abreu is this still happening now that the main screen is the dashboard. Want to know whether we should keep it open or close it...

**Comment by juemura** [comment]
It hasn't happened so far. In fact, I've noticed trips showing up much more quickly now. I'll keep checking though...

**Comment by shankari** [comment]
This still happens. Although we load with the dashboard, it happens when we navigate to the trips screen.

The error when I recently tried it was

```
I/chromium( 7720): [INFO:CONSOLE(156)] "Got event with args {"from":"broadcast","status":"success"}", source: file:///android_asset/www/js/diary/list.js (156)
I/chromium( 7720): [INFO:CONSOLE(26794)] "TypeError: Cannot read property '5809136988f6631c7589c701' of undefined
I/chromium( 7720):     at Object.commonGraph.trip2Common (file:///android_asset/www/js/common/services.js:49:47)
I/chromium( 7720):     at Object.dh.fillCommonTripCount (file:///android_asset/www/js/diary/services.js:248:31)
I/chromium( 7720):     at dh.directiveForTrip (file:///android_asset/www/js/diary/services.js:264:8)
I/chromium( 7720):     at Array.map (native)
I/chromium( 7720):     at file:///android_asset/www/js/diary/list.js:160:72
I/chromium( 7720):     at Scope.$eval (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30395:28)
I/chromium( 7720):     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30495:25)
I/chromium( 7720):     at file:///android_asset/www/js/diary/list.js:157:14
I/chromium( 7720):     at Scope.$broadcast (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30718:28)
I/chromium( 7720):     at processTripsForDay (file:///android_asset/www/js/diary/services.js:518:24)", source: file:///android_asset/www/lib/ionic/js/ionic.bundle.js (26794)
```

**Comment by shankari** [comment]
Full log attached.
[logcat.log.gz](https://github.com/e-mission/e-mission-phone/files/542989/logcat.log.gz)
