### ISSUE TITLE
Retrieving release_notes twice while applying channel update

### ISSUE THREAD

**Issue by shankari** [e-mission/e-mission-phone#286]
While applying the channel update using the custom URL, no release notes were displayed on android. It turned out that this was because the release notes were retrieved twice

```
08-29 17:04:27.601 32432 32432 I chromium: [INFO:CONSOLE(99)] "About to ask for update with release notesversion 2.4.0a,support connection to custom server,switch clients using custom URL scheme", source: file:///android_asset/www/js/splash/updatecheck.js (99)
08-29 17:04:27.628 32432 32432 I chromium: [INFO:CONSOLE(99)] "About to ask for update with release notesversion 2.4.0a,support connection to custom server,switch clients using custom URL scheme,version 2.4.0a,support connection to custom server,switch clients using custom URL scheme", source: file:///android_asset/www/js/splash/updatecheck.js (99)

```

and then angular complained about duplicates in the list.

```
08-29 17:04:27.923 32432 32432 I chromium: [INFO:CONSOLE(26794)] "Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: rn in rn_list, Duplicate key: string:version 2.4.0a, Duplicate value: version 2.4.0a
08-29 17:04:27.923 32432 32432 I chromium: http://errors.angularjs.org/1.5.3/ngRepeat/dupes?p0=rn%20in%20rn_list&p1=string%3Aversion%202.4.0a&p2=version%202.4.0a
08-29 17:04:27.923 32432 32432 I chromium:     at file:///android_asset/www/lib/ionic/js/ionic.bundle.js:13438:12
08-29 17:04:27.923 32432 32432 I chromium:     at ngRepeatAction (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:42169:21)
08-29 17:04:27.923 32432 32432 I chromium:     at $watchCollectionAction (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30102:13)
08-29 17:04:27.923 32432 32432 I chromium:     at Scope.$digest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30239:23)
08-29 17:04:27.923 32432 32432 I chromium:     at Scope.$apply (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:30503:24)
08-29 17:04:27.923 32432 32432 I chromium:     at done (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:24824:47)
08-29 17:04:27.923 32432 32432 I chromium:     at completeRequest (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:25022:7)
08-29 17:04:27.923 32432 32432 I chromium:     at XMLHttpRequest.requestLoaded (file:///android_asset/www/lib/ionic/js/ionic.bundle.js:24963:9)", source: file:///android_asset/www/lib/ionic/js/ionic.bundle.js (26794)
```

**Comment by shankari** [comment]
We should either debug the process that results in multiple updates, or filter out duplicates.
Attached log for future reference.
[duplicate_release_notes_logcat.gz](https://github.com/e-mission/e-mission-phone/files/1311166/duplicate_release_notes_logcat.gz)
