### ISSUE TITLE
bower update fails

### ISSUE THREAD

**Issue by jf87** [e-mission/e-mission-phone#510]
Hi Shankari,

I am trying to follow your instructions and I get the following error in step 6 bower install.
Any idea? 

```
bower string.startsWith#*                                               download https://github.com/MathRobin/string.startsWith/archive/master.tar.gz
util.js:996
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'err',
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "err" argument must be of type negative number
    at Object._errnoException (util.js:996:11)
    at _exceptionWithHostPort (util.js:1024:20)
    at internalConnect (net.js:967:16)
    at GetAddrInfoReqWrap.emitLookup [as callback] (net.js:1114:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:102:10)'''

**Comment by jf87** [comment]
This seems too fix it:

```
rm -rf bower_components
bower cache clean
bower install
```

**Comment by shankari** [comment]
Did it do this while starting from scratch? I don't have CI for the phone builds set up yet, but I do build from scratch occasionally and I haven't seen this. Let me try it again. What version of bower are you running?

**Comment by shankari** [comment]
Also, bower is deprecated, and we should really move away from it
> ...psst! While Bower is maintained, we recommend using Yarn and Webpack or Parcel for front-end projects read how to migrate! 

maybe I should just bite the bullet and do that now, or just use `npm` for everything

**Comment by jf87** [comment]
```
bower --version
1.8.4
```
I think this occurs for me when I run bower twice.
I first followed the instructions for the devapp setup and then did the native setup.
Then this problem occurs.
And yeah, this bower tool seems to be deprecated ;-)
